package com.dayLeasing.dao.model;

// default package
// Generated May 11, 2017 3:45:01 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AreaDates generated by hbm2java
 */
@Entity
@Table(name = "area_dates", catalog = "dayleasing")
public class AreaDates implements java.io.Serializable {

	private Integer id;
	private String uuid;
	private String propertyAreaUuid;
	private Date fromDate;
	private Date toDate;
	private String cost;

	public AreaDates() {
	}

	public AreaDates(String uuid, String propertyAreaUuid, Date fromDate,
			Date toDate, String cost) {
		this.uuid = uuid;
		this.propertyAreaUuid = propertyAreaUuid;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.cost = cost;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "UUID", length = 50)
	public String getUuid() {
		return this.uuid;
	}

	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	@Column(name = "PropertyAreaUUID", length = 50)
	public String getPropertyAreaUuid() {
		return this.propertyAreaUuid;
	}

	public void setPropertyAreaUuid(String propertyAreaUuid) {
		this.propertyAreaUuid = propertyAreaUuid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FromDate", length = 10)
	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ToDate", length = 10)
	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	@Column(name = "Cost", length = 20)
	public String getCost() {
		return this.cost;
	}

	public void setCost(String cost) {
		this.cost = cost;
	}

}
