package com.dayLeasing.dao.model;

// default package
// Generated Apr 11, 2017 7:58:08 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DayleasingUsers generated by hbm2java
 */
@Entity
@Table(name = "dayleasing_users", catalog = "dayleasing")
public class DayleasingUsers implements java.io.Serializable {

	private Integer userId;
	private String userGuid;
	private String fname;
	private String mname;
	private String lname;
	private Date dob;
	private Boolean gender;
	private String address1;
	private String state;
	private String city;
	private String zipCode;
	private String country;
	private String username;
	private String memberType;
	private String emailId;
	private Boolean isActive;
	private String userClass;
	private String address2;
	private String userStatus;
	private Boolean emailValid;
	private String phone;
	private Boolean phoneValid;
	private String guestOf;
	private Date huntDate;
	private String vehicle;
	private String vehicleColor;
	private String vehicleLicense;
	private String huntingLicense;
	private String safetyCourse;
	private String startingField;
	private String currentField;
	private String photo;
	private String source;
	private Date agree;
	private Date createdDate;
	private Date lastLogin;
	private Integer loginCount;
	private String promoCode;

	public DayleasingUsers() {
	}

	public DayleasingUsers(String userGuid) {
		this.userGuid = userGuid;
	}

	public DayleasingUsers(String userGuid, String fname, String mname,
			String lname, Date dob, Boolean gender, String address1,
			String state, String city, String zipCode, String country,
			String username, String memberType, String emailId,
			Boolean isActive, String userClass, String address2,
			String userStatus, Boolean emailValid, String phone,
			Boolean phoneValid, String guestOf, Date huntDate, String vehicle,
			String vehicleColor, String vehicleLicense, String huntingLicense,
			String safetyCourse, String startingField, String currentField,
			String photo, String source, Date agree, Date createdDate,
			Date lastLogin, Integer loginCount, String promoCode) {
		this.userGuid = userGuid;
		this.fname = fname;
		this.mname = mname;
		this.lname = lname;
		this.dob = dob;
		this.gender = gender;
		this.address1 = address1;
		this.state = state;
		this.city = city;
		this.zipCode = zipCode;
		this.country = country;
		this.username = username;
		this.memberType = memberType;
		this.emailId = emailId;
		this.isActive = isActive;
		this.userClass = userClass;
		this.address2 = address2;
		this.userStatus = userStatus;
		this.emailValid = emailValid;
		this.phone = phone;
		this.phoneValid = phoneValid;
		this.guestOf = guestOf;
		this.huntDate = huntDate;
		this.vehicle = vehicle;
		this.vehicleColor = vehicleColor;
		this.vehicleLicense = vehicleLicense;
		this.huntingLicense = huntingLicense;
		this.safetyCourse = safetyCourse;
		this.startingField = startingField;
		this.currentField = currentField;
		this.photo = photo;
		this.source = source;
		this.agree = agree;
		this.createdDate = createdDate;
		this.lastLogin = lastLogin;
		this.loginCount = loginCount;
		this.promoCode = promoCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "UserID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "UserGUID", nullable = false, length = 50)
	public String getUserGuid() {
		return this.userGuid;
	}

	public void setUserGuid(String userGuid) {
		this.userGuid = userGuid;
	}

	@Column(name = "FName")
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "MName")
	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	@Column(name = "LName")
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOB", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "Gender")
	public Boolean getGender() {
		return this.gender;
	}

	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	@Column(name = "Address1")
	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	@Column(name = "State")
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "City")
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "ZipCode", length = 20)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "Country", length = 120)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "Username", length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "MemberType")
	public String getMemberType() {
		return this.memberType;
	}

	public void setMemberType(String memberType) {
		this.memberType = memberType;
	}

	@Column(name = "EmailID")
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "UserClass", length = 20)
	public String getUserClass() {
		return this.userClass;
	}

	public void setUserClass(String userClass) {
		this.userClass = userClass;
	}

	@Column(name = "Address2")
	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	@Column(name = "UserStatus", length = 20)
	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	@Column(name = "EmailValid")
	public Boolean getEmailValid() {
		return this.emailValid;
	}

	public void setEmailValid(Boolean emailValid) {
		this.emailValid = emailValid;
	}

	@Column(name = "Phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "PhoneValid")
	public Boolean getPhoneValid() {
		return this.phoneValid;
	}

	public void setPhoneValid(Boolean phoneValid) {
		this.phoneValid = phoneValid;
	}

	@Column(name = "GuestOf", length = 100)
	public String getGuestOf() {
		return this.guestOf;
	}

	public void setGuestOf(String guestOf) {
		this.guestOf = guestOf;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "HuntDate", length = 10)
	public Date getHuntDate() {
		return this.huntDate;
	}

	public void setHuntDate(Date huntDate) {
		this.huntDate = huntDate;
	}

	@Column(name = "Vehicle", length = 50)
	public String getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(String vehicle) {
		this.vehicle = vehicle;
	}

	@Column(name = "VehicleColor", length = 50)
	public String getVehicleColor() {
		return this.vehicleColor;
	}

	public void setVehicleColor(String vehicleColor) {
		this.vehicleColor = vehicleColor;
	}

	@Column(name = "VehicleLicense", length = 50)
	public String getVehicleLicense() {
		return this.vehicleLicense;
	}

	public void setVehicleLicense(String vehicleLicense) {
		this.vehicleLicense = vehicleLicense;
	}

	@Column(name = "HuntingLicense", length = 50)
	public String getHuntingLicense() {
		return this.huntingLicense;
	}

	public void setHuntingLicense(String huntingLicense) {
		this.huntingLicense = huntingLicense;
	}

	@Column(name = "SafetyCourse", length = 50)
	public String getSafetyCourse() {
		return this.safetyCourse;
	}

	public void setSafetyCourse(String safetyCourse) {
		this.safetyCourse = safetyCourse;
	}

	@Column(name = "StartingField", length = 50)
	public String getStartingField() {
		return this.startingField;
	}

	public void setStartingField(String startingField) {
		this.startingField = startingField;
	}

	@Column(name = "CurrentField", length = 50)
	public String getCurrentField() {
		return this.currentField;
	}

	public void setCurrentField(String currentField) {
		this.currentField = currentField;
	}

	@Column(name = "Photo")
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "Source", length = 50)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "Agree", length = 10)
	public Date getAgree() {
		return this.agree;
	}

	public void setAgree(Date agree) {
		this.agree = agree;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastLogin", length = 19)
	public Date getLastLogin() {
		return this.lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}

	@Column(name = "LoginCount")
	public Integer getLoginCount() {
		return this.loginCount;
	}

	public void setLoginCount(Integer loginCount) {
		this.loginCount = loginCount;
	}

	@Column(name = "PromoCode", length = 20)
	public String getPromoCode() {
		return this.promoCode;
	}

	public void setPromoCode(String promoCode) {
		this.promoCode = promoCode;
	}

}
