package com.dayLeasing.dao.model;

// default package
// Generated Jun 8, 2017 2:53:48 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Propertyreservation generated by hbm2java
 */
@Entity
@Table(name = "propertyreservation", catalog = "dayleasing")
public class Propertyreservation implements java.io.Serializable {

	private Integer propertyReservationId;
	private String propertyReservationUuid;
	private String propertyUuid;
	private String propertyAreaUuid;
	private String propertySlotsUuid;
	private String userGuid;
	private Date reservationFrom;
	private Date reservationTo;
	private String price;
	private String paymentStatus;
	private String paymentSuccessId;
	private String paymentFailureId;
	private String paymentCancelId;
	private String refundId;
	private Date created;
	private Date lastModified;
	private String cartId;
	private String propertyName;
	private String areaName;
	private String slotName;
	private String userName;
	private String paymentMailId;
	private String couponCode;
	private String cartPrice;

	public Propertyreservation() {
	}

	public Propertyreservation(Date created, Date lastModified) {
		this.created = created;
		this.lastModified = lastModified;
	}

	public Propertyreservation(String propertyReservationUuid,
			String propertyUuid, String propertyAreaUuid,
			String propertySlotsUuid, String userGuid, Date reservationFrom,
			Date reservationTo, String price, String paymentStatus,
			String paymentSuccessId, String paymentFailureId,
			String paymentCancelId, String refundId, Date created,
			Date lastModified, String cartId, String propertyName,
			String areaName, String slotName, String userName,
			String paymentMailId, String couponCode) {
		this.propertyReservationUuid = propertyReservationUuid;
		this.propertyUuid = propertyUuid;
		this.propertyAreaUuid = propertyAreaUuid;
		this.propertySlotsUuid = propertySlotsUuid;
		this.userGuid = userGuid;
		this.reservationFrom = reservationFrom;
		this.reservationTo = reservationTo;
		this.price = price;
		this.paymentStatus = paymentStatus;
		this.paymentSuccessId = paymentSuccessId;
		this.paymentFailureId = paymentFailureId;
		this.paymentCancelId = paymentCancelId;
		this.refundId = refundId;
		this.created = created;
		this.lastModified = lastModified;
		this.cartId = cartId;
		this.propertyName = propertyName;
		this.areaName = areaName;
		this.slotName = slotName;
		this.userName = userName;
		this.paymentMailId = paymentMailId;
		this.couponCode = couponCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PropertyReservationID", unique = true, nullable = false)
	public Integer getPropertyReservationId() {
		return this.propertyReservationId;
	}

	public void setPropertyReservationId(Integer propertyReservationId) {
		this.propertyReservationId = propertyReservationId;
	}

	@Column(name = "PropertyReservationUUID", length = 50)
	public String getPropertyReservationUuid() {
		return this.propertyReservationUuid;
	}

	public void setPropertyReservationUuid(String propertyReservationUuid) {
		this.propertyReservationUuid = propertyReservationUuid;
	}

	@Column(name = "PropertyUUID", length = 50)
	public String getPropertyUuid() {
		return this.propertyUuid;
	}

	public void setPropertyUuid(String propertyUuid) {
		this.propertyUuid = propertyUuid;
	}

	@Column(name = "PropertyAreaUUID", length = 50)
	public String getPropertyAreaUuid() {
		return this.propertyAreaUuid;
	}

	public void setPropertyAreaUuid(String propertyAreaUuid) {
		this.propertyAreaUuid = propertyAreaUuid;
	}

	@Column(name = "PropertySlotsUUID", length = 50)
	public String getPropertySlotsUuid() {
		return this.propertySlotsUuid;
	}

	public void setPropertySlotsUuid(String propertySlotsUuid) {
		this.propertySlotsUuid = propertySlotsUuid;
	}

	@Column(name = "UserGUID")
	public String getUserGuid() {
		return this.userGuid;
	}

	public void setUserGuid(String userGuid) {
		this.userGuid = userGuid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ReservationFrom", length = 19)
	public Date getReservationFrom() {
		return this.reservationFrom;
	}

	public void setReservationFrom(Date reservationFrom) {
		this.reservationFrom = reservationFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ReservationTo", length = 19)
	public Date getReservationTo() {
		return this.reservationTo;
	}

	public void setReservationTo(Date reservationTo) {
		this.reservationTo = reservationTo;
	}

	@Column(name = "Price", length = 10)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	@Column(name = "PaymentStatus", length = 10)
	public String getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	@Column(name = "PaymentSuccessId", length = 50)
	public String getPaymentSuccessId() {
		return this.paymentSuccessId;
	}

	public void setPaymentSuccessId(String paymentSuccessId) {
		this.paymentSuccessId = paymentSuccessId;
	}

	@Column(name = "PaymentFailureId", length = 50)
	public String getPaymentFailureId() {
		return this.paymentFailureId;
	}

	public void setPaymentFailureId(String paymentFailureId) {
		this.paymentFailureId = paymentFailureId;
	}

	@Column(name = "PaymentCancelId", length = 50)
	public String getPaymentCancelId() {
		return this.paymentCancelId;
	}

	public void setPaymentCancelId(String paymentCancelId) {
		this.paymentCancelId = paymentCancelId;
	}

	@Column(name = "RefundId", length = 50)
	public String getRefundId() {
		return this.refundId;
	}

	public void setRefundId(String refundId) {
		this.refundId = refundId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "Created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LastModified", nullable = false, length = 19)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "CartId", length = 50)
	public String getCartId() {
		return this.cartId;
	}

	public void setCartId(String cartId) {
		this.cartId = cartId;
	}

	@Column(name = "PropertyName", length = 20)
	public String getPropertyName() {
		return this.propertyName;
	}

	public void setPropertyName(String propertyName) {
		this.propertyName = propertyName;
	}

	@Column(name = "AreaName", length = 20)
	public String getAreaName() {
		return this.areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName;
	}

	@Column(name = "SlotName", length = 20)
	public String getSlotName() {
		return this.slotName;
	}

	public void setSlotName(String slotName) {
		this.slotName = slotName;
	}

	@Column(name = "UserName", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PaymentMailId", length = 50)
	public String getPaymentMailId() {
		return this.paymentMailId;
	}

	public void setPaymentMailId(String paymentMailId) {
		this.paymentMailId = paymentMailId;
	}

	@Column(name = "CouponCode", length = 50)
	public String getCouponCode() {
		return this.couponCode;
	}

	public void setCouponCode(String couponCode) {
		this.couponCode = couponCode;
	}

	public String getCartPrice() {
		return cartPrice;
	}
	
	@Column(name = "CartPrice", length = 20)
	public void setCartPrice(String cartPrice) {
		this.cartPrice = cartPrice;
	}

}
