package com.dayLeasing.dao.model;

// default package
// Generated May 4, 2017 3:47:24 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Propertyslots generated by hbm2java
 */
@Entity
@Table(name = "propertyslots", catalog = "dayleasing")
public class Propertyslots implements java.io.Serializable {

	private Integer propertySlotsId;
	private String propertySlotsUuid;
	private String propertyUuid;
	private String propertyAreaUuid;
	private Integer slotId;
	private String slotName;
	private Date slotFrom;
	private Date slotTo;
	private String slotSize;
	private String outLine;
	private Boolean isActive;
	private String center;
	private String slotPrice;
	private String maxHunter;
	
	public Propertyslots() {
	}

	public Propertyslots(String propertySlotsUuid) {
		this.propertySlotsUuid = propertySlotsUuid;
	}

	public Propertyslots(String propertySlotsUuid, String propertyUuid,
			String propertyAreaUuid, Integer slotId, String slotName,
			Date slotFrom, Date slotTo, String slotSize, String outLine,
			Boolean isActive, String center, String slotPrice, String maxHunter) {
		this.propertySlotsUuid = propertySlotsUuid;
		this.propertyUuid = propertyUuid;
		this.propertyAreaUuid = propertyAreaUuid;
		this.slotId = slotId;
		this.slotName = slotName;
		this.slotFrom = slotFrom;
		this.slotTo = slotTo;
		this.slotSize = slotSize;
		this.outLine = outLine;
		this.isActive = isActive;
		this.center = center;
		this.slotPrice = slotPrice;
		this.maxHunter = maxHunter;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PropertySlotsID", unique = true, nullable = false)
	public Integer getPropertySlotsId() {
		return this.propertySlotsId;
	}

	public void setPropertySlotsId(Integer propertySlotsId) {
		this.propertySlotsId = propertySlotsId;
	}

	@Column(name = "PropertySlotsUUID", nullable = false, length = 50)
	public String getPropertySlotsUuid() {
		return this.propertySlotsUuid;
	}

	public void setPropertySlotsUuid(String propertySlotsUuid) {
		this.propertySlotsUuid = propertySlotsUuid;
	}

	@Column(name = "PropertyUUID", length = 50)
	public String getPropertyUuid() {
		return this.propertyUuid;
	}

	public void setPropertyUuid(String propertyUuid) {
		this.propertyUuid = propertyUuid;
	}

	@Column(name = "PropertyAreaUUID", length = 50)
	public String getPropertyAreaUuid() {
		return this.propertyAreaUuid;
	}

	public void setPropertyAreaUuid(String propertyAreaUuid) {
		this.propertyAreaUuid = propertyAreaUuid;
	}

	@Column(name = "SlotID")
	public Integer getSlotId() {
		return this.slotId;
	}

	public void setSlotId(Integer slotId) {
		this.slotId = slotId;
	}

	@Column(name = "SlotName")
	public String getSlotName() {
		return this.slotName;
	}

	public void setSlotName(String slotName) {
		this.slotName = slotName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SlotFrom", length = 19)
	public Date getSlotFrom() {
		return this.slotFrom;
	}

	public void setSlotFrom(Date slotFrom) {
		this.slotFrom = slotFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SlotTo", length = 19)
	public Date getSlotTo() {
		return this.slotTo;
	}

	public void setSlotTo(Date slotTo) {
		this.slotTo = slotTo;
	}

	@Column(name = "SlotSize", length = 20)
	public String getSlotSize() {
		return this.slotSize;
	}

	public void setSlotSize(String slotSize) {
		this.slotSize = slotSize;
	}

	@Column(name = "OutLine", length = 16777215)
	public String getOutLine() {
		return this.outLine;
	}

	public void setOutLine(String outLine) {
		this.outLine = outLine;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "Center")
	public String getCenter() {
		return this.center;
	}

	public void setCenter(String center) {
		this.center = center;
	}

	@Column(name = "SlotPrice", length = 20)
	public String getSlotPrice() {
		return this.slotPrice;
	}

	public void setSlotPrice(String slotPrice) {
		this.slotPrice = slotPrice;
	}

	@Column(name = "MaxHunter", length = 20)
	public String getMaxHunter() {
		return this.maxHunter;
	}

	public void setMaxHunter(String maxHunter) {
		this.maxHunter = maxHunter;
	}

}
