package com.dayLeasing.dao.model;

// default package
// Generated May 4, 2017 3:47:24 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Propertyarea generated by hbm2java
 */
@Entity
@Table(name = "propertyarea", catalog = "dayleasing")
public class Propertyarea implements java.io.Serializable {

	private Integer propertyAreaId;
	private String propertyAreaUuid;
	private String propertyUuid;
	private String propertyAreaName;
	private String propertyHiddenAreaName;
	private String propertyAreaNote;
	private String propertySlots;
	private String propertySize;
	private String propertyPrice;
	private String maxHunter;
	private String outLine;
	private Boolean isActive;

	public Propertyarea() {
	}

	public Propertyarea(String propertyAreaUuid) {
		this.propertyAreaUuid = propertyAreaUuid;
	}

	public Propertyarea(String propertyAreaUuid, String propertyUuid,
			String propertyAreaName, String propertyAreaNote,
			String propertySlots, String propertySize, String propertyPrice,
			String maxHunter, String outLine, Boolean isActive) {
		this.propertyAreaUuid = propertyAreaUuid;
		this.propertyUuid = propertyUuid;
		this.propertyAreaName = propertyAreaName;
		this.propertyAreaNote = propertyAreaNote;
		this.propertySlots = propertySlots;
		this.propertySize = propertySize;
		this.propertyPrice = propertyPrice;
		this.maxHunter = maxHunter;
		this.outLine = outLine;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PropertyAreaID", unique = true, nullable = false)
	public Integer getPropertyAreaId() {
		return this.propertyAreaId;
	}

	public void setPropertyAreaId(Integer propertyAreaId) {
		this.propertyAreaId = propertyAreaId;
	}

	@Column(name = "PropertyAreaUUID", nullable = false, length = 50)
	public String getPropertyAreaUuid() {
		return this.propertyAreaUuid;
	}

	public void setPropertyAreaUuid(String propertyAreaUuid) {
		this.propertyAreaUuid = propertyAreaUuid;
	}

	@Column(name = "PropertyUUID", length = 50)
	public String getPropertyUuid() {
		return this.propertyUuid;
	}

	public void setPropertyUuid(String propertyUuid) {
		this.propertyUuid = propertyUuid;
	}

	@Column(name = "PropertyAreaName", length = 100)
	public String getPropertyAreaName() {
		return this.propertyAreaName;
	}

	public void setPropertyAreaName(String propertyAreaName) {
		this.propertyAreaName = propertyAreaName;
	}

	@Column(name = "PropertyHiddenAreaName", length = 100)
	public String getPropertyHiddenAreaName() {
		return propertyHiddenAreaName;
	}

	public void setPropertyHiddenAreaName(String propertyHiddenAreaName) {
		this.propertyHiddenAreaName = propertyHiddenAreaName;
	}

	@Column(name = "PropertyAreaNote")
	public String getPropertyAreaNote() {
		return this.propertyAreaNote;
	}

	public void setPropertyAreaNote(String propertyAreaNote) {
		this.propertyAreaNote = propertyAreaNote;
	}

	@Column(name = "PropertySlots", length = 10)
	public String getPropertySlots() {
		return this.propertySlots;
	}

	public void setPropertySlots(String propertySlots) {
		this.propertySlots = propertySlots;
	}

	@Column(name = "PropertySize", length = 20)
	public String getPropertySize() {
		return this.propertySize;
	}

	public void setPropertySize(String propertySize) {
		this.propertySize = propertySize;
	}

	@Column(name = "PropertyPrice", length = 6)
	public String getPropertyPrice() {
		return this.propertyPrice;
	}

	public void setPropertyPrice(String propertyPrice) {
		this.propertyPrice = propertyPrice;
	}

	@Column(name = "MaxHunter", length = 20)
	public String getMaxHunter() {
		return this.maxHunter;
	}

	public void setMaxHunter(String maxHunter) {
		this.maxHunter = maxHunter;
	}

	@Column(name = "OutLine", length = 16777215)
	public String getOutLine() {
		return this.outLine;
	}

	public void setOutLine(String outLine) {
		this.outLine = outLine;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

}
