package com.dayLeasing.dao.model;

// default package
// Generated Mar 24, 2017 1:05:18 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// TODO: Auto-generated Javadoc
/**
 * Testtable generated by hbm2java.
 */
/**
 * @author Balaram
 *
 */
@Entity
@Table(name = "testtable", catalog = "dayleasing")
public class Testtable implements java.io.Serializable {

  /** The sno. */
  private int sno;

  /** The name. */
  private String name;

  /** The address. */
  private String address;

  /**
   * Instantiates a new testtable.
   */
  public Testtable() {
  }

  /**
   * Instantiates a new testtable.
   *
   * @param sno
   *          the sno
   */
  public Testtable(int sno) {
    this.sno = sno;
  }

  /**
   * Instantiates a new testtable.
   *
   * @param sno
   *          the sno
   * @param name
   *          the name
   * @param address
   *          the address
   */
  public Testtable(int sno, String name, String address) {
    this.sno = sno;
    this.name = name;
    this.address = address;
  }

  /**
   * Gets the sno.
   *
   * @return the sno
   */
  @Id
  @Column(name = "sno", unique = true, nullable = false)
  public int getSno() {
    return this.sno;
  }

  /**
   * Sets the sno.
   *
   * @param sno
   *          the new sno
   */
  public void setSno(int sno) {
    this.sno = sno;
  }

  /**
   * Gets the name.
   *
   * @return the name
   */
  @Column(name = "name", length = 20)
  public String getName() {
    return this.name;
  }

  /**
   * Sets the name.
   *
   * @param name
   *          the new name
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Gets the address.
   *
   * @return the address
   */
  @Column(name = "address", length = 20)
  public String getAddress() {
    return this.address;
  }

  /**
   * Sets the address.
   *
   * @param address
   *          the new address
   */
  public void setAddress(String address) {
    this.address = address;
  }

}
