package com.dayLeasing.dao.model;

// default package
// Generated Apr 11, 2017 7:58:08 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Types generated by hbm2java
 */
@Entity
@Table(name = "types", catalog = "dayleasing")
public class Types implements java.io.Serializable {

	private Integer typeId;
	private String typeName;
	private Boolean isActive;

	public Types() {
	}

	public Types(String typeName, Boolean isActive) {
		this.typeName = typeName;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "TypeID", unique = true, nullable = false)
	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	@Column(name = "TypeName")
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "IsActive")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}

}
